name: Deploy to Firebase Hosting on PR
'on': push
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "REACT_APP_FIREBASE_API_KEY='${{ secrets.FIREBASE_API_KEY }}'" >> .env
      - run: echo "REACT_APP_FIREBASE_DOMAIN_URL='${{ secrets.FIREBASE_AUTH_DOMAIN }}'" >> .env
      - run:  npm build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUILDPIPE_TEST }}'
          projectId: buildpipe-test
